#!/bin/sh

deps=
for d in deps/* ; do
  deps="$deps -pa $d/ebin"
done
exec erl \
  -boot start_sasl \
  -name md_server -setcookie md_server \
  $deps \
  -pa ebin \
  -config mondemand_server.config \
  -config mondemand_server_dev.config \
  -s reloader \
  -s mondemand_server_app
